import type { Cliente, Colaborador, Equipo, Usuario, ActaCalidad, ActaRecepcion, OrdenTrabajo, AsignacionTarea } from "./types";
import { createEmptyRespuestas } from "./checklist-data";
import { createEmptyRespuestasRecepcion } from "./recepcion-data";

export const clientesIniciales: Cliente[] = [
  {
    id: "c1",
    razonSocial: "Minera Los Andes SpA",
    rut: "76.543.210-1",
    giro: "Extracción de cobre",
    direccion: "Camino Minero Km 45",
    comuna: "Copiapó",
    ciudad: "Copiapó",
    telefono: "+56 9 8765 4321",
    email: "contacto@losandes.cl",
    contactoNombre: "Carlos Mendoza",
    contactoCargo: "Jefe de Mantención",
    contactoTelefono: "+56 9 1234 5678",
    contactoEmail: "cmendoza@losandes.cl",
    notas: "Cliente preferencial. Facturación a 30 días.",
    createdAt: "2025-06-15",
  },
  {
    id: "c2",
    razonSocial: "Constructora del Norte Ltda.",
    rut: "77.234.567-8",
    giro: "Construcción de obras civiles",
    direccion: "Av. Industrial 1200",
    comuna: "Antofagasta",
    ciudad: "Antofagasta",
    telefono: "+56 55 234 5678",
    email: "info@constructoranorte.cl",
    contactoNombre: "María González",
    contactoCargo: "Gerente de Operaciones",
    contactoTelefono: "+56 9 9876 5432",
    contactoEmail: "mgonzalez@constructoranorte.cl",
    notas: "",
    createdAt: "2025-08-20",
  },
  {
    id: "c3",
    razonSocial: "Forestal Arauco S.A.",
    rut: "96.505.760-9",
    giro: "Explotación forestal",
    direccion: "Ruta 5 Sur Km 890",
    comuna: "Concepción",
    ciudad: "Concepción",
    telefono: "+56 41 345 6789",
    email: "mantencion@arauco.cl",
    contactoNombre: "Pedro Soto",
    contactoCargo: "Supervisor de Flota",
    contactoTelefono: "+56 9 7654 3210",
    contactoEmail: "psoto@arauco.cl",
    notas: "Requiere informes semanales de avance.",
    createdAt: "2025-10-01",
  },
];

export const equiposIniciales: Equipo[] = [
  {
    id: "e1",
    marca: "Caterpillar",
    modelo: "320D",
    anio: 2019,
    nroSerie: "CAT0320DKFME01234",
    nroMotor: "C6.6-789012",
    propietarioId: "c1",
    estado: "reparacion",
    fechaIngreso: "2026-02-15",
    descripcionTrabajo: "Reparación de sistema hidráulico principal",
  },
  {
    id: "e2",
    marca: "Komatsu",
    modelo: "PC200-8",
    anio: 2021,
    nroSerie: "KMTPC200AB1234567",
    nroMotor: "SAA6D107E-456789",
    propietarioId: "c2",
    estado: "espera_repuestos",
    fechaIngreso: "2026-02-20",
    descripcionTrabajo: "Cambio de tren de rodaje - esperando repuestos importados",
  },
  {
    id: "e3",
    marca: "Volvo",
    modelo: "EC210B",
    anio: 2020,
    nroSerie: "VCE0210BCD9876543",
    nroMotor: "D6E-321098",
    propietarioId: "c1",
    estado: "en_taller",
    fechaIngreso: "2026-03-01",
    descripcionTrabajo: "Mantención preventiva 2000 hrs",
  },
  {
    id: "e4",
    marca: "Hitachi",
    modelo: "ZX200-5",
    anio: 2018,
    nroSerie: "HCMZX200EF5678901",
    nroMotor: "ISUZU-654321",
    propietarioId: "c3",
    estado: "reparacion",
    fechaIngreso: "2026-02-28",
    descripcionTrabajo: "Reparación de motor - rectificación de cilindros",
  },
  {
    id: "e5",
    marca: "Caterpillar",
    modelo: "D6T",
    anio: 2017,
    nroSerie: "CATD6TXYZ1122334",
    nroMotor: "C9.3-998877",
    propietarioId: "c2",
    estado: "espera_repuestos",
    fechaIngreso: "2026-03-05",
    descripcionTrabajo: "Cambio de transmisión - repuesto en tránsito desde USA",
  },
  {
    id: "e6",
    marca: "JCB",
    modelo: "JS220",
    anio: 2022,
    nroSerie: "JCB220LCX4455667",
    nroMotor: "JCB444-778899",
    propietarioId: "c3",
    estado: "en_taller",
    fechaIngreso: "2026-03-08",
    descripcionTrabajo: "Revisión general pre-temporada",
  },
];

export const colaboradoresIniciales: Colaborador[] = [
  {
    id: "col1",
    nombre: "Roberto Fuentes",
    rut: "12.345.678-9",
    cargo: "Mecánico Jefe",
    especialidad: "Motores diésel",
    telefono: "+56 9 1111 2222",
    email: "rfuentes@sm-em.cl",
    activo: true,
    fechaIngreso: "2018-03-15",
  },
  {
    id: "col2",
    nombre: "Andrea Vega",
    rut: "13.456.789-0",
    cargo: "Técnico Hidráulico",
    especialidad: "Sistemas hidráulicos",
    telefono: "+56 9 3333 4444",
    email: "avega@sm-em.cl",
    activo: true,
    fechaIngreso: "2020-07-01",
  },
  {
    id: "col3",
    nombre: "Luis Herrera",
    rut: "14.567.890-1",
    cargo: "Soldador",
    especialidad: "Soldadura estructural",
    telefono: "+56 9 5555 6666",
    email: "lherrera@sm-em.cl",
    activo: true,
    fechaIngreso: "2019-11-20",
  },
  {
    id: "col4",
    nombre: "Patricia Muñoz",
    rut: "15.678.901-2",
    cargo: "Recepcionista",
    especialidad: "Atención al cliente",
    telefono: "+56 9 7777 8888",
    email: "pmunoz@sm-em.cl",
    activo: true,
    fechaIngreso: "2021-01-10",
  },
];

export const usuariosIniciales: Usuario[] = [
  {
    id: "u1",
    nombre: "Admin Sistema",
    email: "admin@sm-em.cl",
    rol: "admin",
    colaboradorId: null,
    permisos: null,
    activo: true,
    ultimoAcceso: "2026-03-10 09:15",
  },
  {
    id: "u2",
    nombre: "Roberto Fuentes",
    email: "rfuentes@sm-em.cl",
    rol: "supervisor",
    colaboradorId: "col1",
    permisos: null,
    activo: true,
    ultimoAcceso: "2026-03-10 08:30",
  },
  {
    id: "u3",
    nombre: "Andrea Vega",
    email: "avega@sm-em.cl",
    rol: "tecnico",
    colaboradorId: "col2",
    permisos: null,
    activo: true,
    ultimoAcceso: "2026-03-09 17:45",
  },
  {
    id: "u4",
    nombre: "Patricia Muñoz",
    email: "pmunoz@sm-em.cl",
    rol: "recepcion",
    colaboradorId: "col4",
    permisos: null,
    activo: true,
    ultimoAcceso: "2026-03-10 07:50",
  },
  {
    id: "u5",
    nombre: "Luis Herrera",
    email: "lherrera@sm-em.cl",
    rol: "tecnico",
    colaboradorId: "col3",
    permisos: null,
    activo: true,
    ultimoAcceso: "2026-03-10 07:00",
  },
];

const respuestasDemo = createEmptyRespuestas();
respuestasDemo["md_01"] = { estado: "R", observaciones: "" };
respuestasDemo["md_02"] = { estado: "R", observaciones: "" };
respuestasDemo["md_03"] = { estado: "P", observaciones: "Requiere cambio de correa" };
respuestasDemo["tr_01"] = { estado: "R", observaciones: "" };
respuestasDemo["tr_02"] = { estado: "R", observaciones: "" };
respuestasDemo["fr_01"] = { estado: "R", observaciones: "" };
respuestasDemo["el_04"] = { estado: "P", observaciones: "Batería con baja carga" };

export const actasIniciales: ActaCalidad[] = [
  {
    id: "acta1",
    tipoActa: "Ingreso a taller",
    fecha: "2026-02-15",
    equipoId: "e1",
    tipoTrabajo: "Reparación de sistema hidráulico principal",
    horasMotor: "8.450",
    horasTransmision: "8.420",
    respuestas: respuestasDemo,
    responsableEvaluacion: "Roberto Fuentes",
    supervisorCargo: "Admin Sistema",
    estado: "borrador",
    createdAt: "2026-02-15",
  },
  {
    id: "acta2",
    tipoActa: "Control intermedio",
    fecha: "2026-03-01",
    equipoId: "e3",
    tipoTrabajo: "Mantención preventiva 2000 hrs",
    horasMotor: "2.015",
    horasTransmision: "2.010",
    respuestas: createEmptyRespuestas(),
    responsableEvaluacion: "Andrea Vega",
    supervisorCargo: "Roberto Fuentes",
    estado: "completada",
    createdAt: "2026-03-01",
  },
];

const respuestasRecepcionDemo = createEmptyRespuestasRecepcion();
respuestasRecepcionDemo["md_01"] = { estado: "B", observaciones: "" };
respuestasRecepcionDemo["md_02"] = { estado: "B", observaciones: "" };
respuestasRecepcionDemo["md_03"] = { estado: "R", observaciones: "Desgaste leve" };
respuestasRecepcionDemo["es_12"] = { estado: "M", observaciones: "Neumático P1 desgastado" };
respuestasRecepcionDemo["fr_01"] = { estado: "B", observaciones: "" };
respuestasRecepcionDemo["sg_10"] = { estado: "NA", observaciones: "No aplica en este modelo" };

export const actasRecepcionIniciales: ActaRecepcion[] = [
  {
    id: "rec1",
    tipoActa: "Recepción de equipo",
    fecha: "2026-02-15",
    equipoId: "e1",
    tipoTrabajo: "Ingreso por reparación sistema hidráulico",
    horasMotor: "8.450",
    horasTransmision: "8.420",
    respuestas: respuestasRecepcionDemo,
    responsableEvaluacion: "Patricia Muñoz",
    supervisorCargo: "Roberto Fuentes",
    estado: "completada",
    createdAt: "2026-02-15",
  },
  {
    id: "rec2",
    tipoActa: "Entrega de equipo",
    fecha: "2026-03-08",
    equipoId: "e6",
    tipoTrabajo: "Revisión general pre-temporada",
    horasMotor: "1.200",
    horasTransmision: "1.195",
    respuestas: createEmptyRespuestasRecepcion(),
    responsableEvaluacion: "Andrea Vega",
    supervisorCargo: "Roberto Fuentes",
    estado: "borrador",
    createdAt: "2026-03-08",
  },
];

export const ordenesIniciales: OrdenTrabajo[] = [
  {
    id: "ot1",
    numeroOT: "OT-2026-0041",
    descripcion: "Reparación sistema hidráulico principal",
    equipoId: "e1",
    personalCargo: "Roberto Fuentes",
    ubicacion: "taller",
    etapa: "reparacion",
    estado: "activa",
    horometroDiesel: "8.450",
    kilometraje: "—",
    descripcionTrabajo: "Cambio de bomba hidráulica y rectificación de cilindros",
    fechaInicio: "2026-02-16",
    horaInicio: "08:30",
    fechaTermino: "",
    horaTermino: "",
    repuestos: [
      { item: 1, nroParte: "CAT-123456", descripcion: "Bomba hidráulica", cantidad: 1 },
      { item: 2, nroParte: "CAT-789012", descripcion: "Kit sellos cilindro", cantidad: 2 },
    ],
    observaciones: "",
    createdAt: "2026-02-16",
  },
  {
    id: "ot2",
    numeroOT: "OT-2026-0042",
    descripcion: "Cambio tren de rodaje",
    equipoId: "e2",
    personalCargo: "Andrea Vega",
    ubicacion: "taller",
    etapa: "desmontaje",
    estado: "pausada",
    horometroDiesel: "12.200",
    kilometraje: "—",
    descripcionTrabajo: "Espera repuestos importados — desmontaje parcial realizado",
    fechaInicio: "2026-02-21",
    horaInicio: "07:45",
    fechaTermino: "",
    horaTermino: "",
    repuestos: [],
    observaciones: "Pausada por falta de repuestos",
    createdAt: "2026-02-21",
  },
  {
    id: "ot3",
    numeroOT: "OT-2026-0043",
    descripcion: "Mantención preventiva 2000 hrs",
    equipoId: "e3",
    personalCargo: "Roberto Fuentes",
    ubicacion: "taller",
    etapa: "mantencion",
    estado: "activa",
    horometroDiesel: "2.015",
    kilometraje: "—",
    descripcionTrabajo: "Cambio filtros, aceite y revisión general",
    fechaInicio: "2026-03-02",
    horaInicio: "09:00",
    fechaTermino: "",
    horaTermino: "",
    repuestos: [
      { item: 1, nroParte: "VOL-334455", descripcion: "Filtro aceite motor", cantidad: 1 },
    ],
    observaciones: "",
    createdAt: "2026-03-02",
  },
  {
    id: "ot4",
    numeroOT: "OT-2026-0044",
    descripcion: "Rectificación motor — cilindros",
    equipoId: "e4",
    personalCargo: "Roberto Fuentes",
    ubicacion: "taller",
    etapa: "normalizacion",
    estado: "activa",
    horometroDiesel: "6.800",
    kilometraje: "—",
    descripcionTrabajo: "Motor desmontado, en proceso de normalización",
    fechaInicio: "2026-03-01",
    horaInicio: "08:00",
    fechaTermino: "",
    horaTermino: "",
    repuestos: [],
    observaciones: "",
    createdAt: "2026-03-01",
  },
  {
    id: "ot5",
    numeroOT: "OT-2026-0045",
    descripcion: "Cambio transmisión",
    equipoId: "e5",
    personalCargo: "Luis Herrera",
    ubicacion: "taller",
    etapa: "montaje",
    estado: "activa",
    horometroDiesel: "9.100",
    kilometraje: "—",
    descripcionTrabajo: "Transmisión nueva recibida, iniciando montaje",
    fechaInicio: "2026-03-06",
    horaInicio: "08:15",
    fechaTermino: "",
    horaTermino: "",
    repuestos: [
      { item: 1, nroParte: "CAT-D6T-TRX", descripcion: "Transmisión completa", cantidad: 1 },
    ],
    observaciones: "",
    createdAt: "2026-03-06",
  },
  {
    id: "ot6",
    numeroOT: "OT-2026-0046",
    descripcion: "Revisión general pre-temporada",
    equipoId: "e6",
    personalCargo: "Andrea Vega",
    ubicacion: "terreno",
    etapa: "evaluacion",
    estado: "activa",
    horometroDiesel: "1.200",
    kilometraje: "—",
    descripcionTrabajo: "Evaluación en faena forestal",
    fechaInicio: "2026-03-09",
    horaInicio: "07:30",
    fechaTermino: "",
    horaTermino: "",
    repuestos: [],
    observaciones: "Trabajo en terreno — cliente Forestal Arauco",
    createdAt: "2026-03-09",
  },
  {
    id: "ot7",
    numeroOT: "OT-2026-0038",
    descripcion: "Reparación estructural chasis",
    equipoId: "e2",
    personalCargo: "Luis Herrera",
    ubicacion: "taller",
    etapa: "soldadura",
    estado: "terminada",
    horometroDiesel: "11.950",
    kilometraje: "—",
    descripcionTrabajo: "Soldadura de fisuras en chasis — completado",
    fechaInicio: "2026-01-10",
    horaInicio: "08:00",
    fechaTermino: "2026-01-25",
    horaTermino: "17:30",
    repuestos: [],
    observaciones: "OT cerrada satisfactoriamente",
    createdAt: "2026-01-10",
  },
  {
    id: "ot8",
    numeroOT: "OT-2026-0047",
    descripcion: "Prueba post-reparación hidráulica",
    equipoId: "e1",
    personalCargo: "Andrea Vega",
    ubicacion: "taller",
    etapa: "prueba",
    estado: "activa",
    horometroDiesel: "8.450",
    kilometraje: "—",
    descripcionTrabajo: "Pruebas de presión y funcionamiento",
    fechaInicio: "2026-03-10",
    horaInicio: "10:00",
    fechaTermino: "",
    horaTermino: "",
    repuestos: [],
    observaciones: "",
    createdAt: "2026-03-10",
  },
];

export const asignacionesIniciales: AsignacionTarea[] = [
  {
    id: "asg1",
    ordenId: "ot1",
    etapa: "reparacion",
    colaboradorId: "col2",
    asignadoPorId: "u2",
    estado: "en_proceso",
    instrucciones: "Revisar bomba hidráulica y sellos. Reportar cualquier fuga.",
    comentarioMecanico: "",
    fechaAsignacion: "2026-02-16",
    fechaActualizacion: "2026-02-17",
  },
  {
    id: "asg2",
    ordenId: "ot1",
    etapa: "prueba",
    colaboradorId: "col2",
    asignadoPorId: "u2",
    estado: "pendiente",
    instrucciones: "Realizar prueba de presión al finalizar reparación.",
    comentarioMecanico: "",
    fechaAsignacion: "2026-03-10",
    fechaActualizacion: "2026-03-10",
  },
  {
    id: "asg3",
    ordenId: "ot4",
    etapa: "normalizacion",
    colaboradorId: "col1",
    asignadoPorId: "u2",
    estado: "completada",
    instrucciones: "Rectificación de cilindros — motor desmontado.",
    comentarioMecanico: "Cilindros rectificados dentro de tolerancia.",
    fechaAsignacion: "2026-03-01",
    fechaActualizacion: "2026-03-05",
  },
  {
    id: "asg4",
    ordenId: "ot5",
    etapa: "montaje",
    colaboradorId: "col3",
    asignadoPorId: "u1",
    estado: "con_observaciones",
    instrucciones: "Montaje de transmisión nueva. Verificar alineación.",
    comentarioMecanico: "Falta grapa de sujeción lateral — solicitar repuesto.",
    fechaAsignacion: "2026-03-06",
    fechaActualizacion: "2026-03-08",
  },
  {
    id: "asg5",
    ordenId: "ot2",
    etapa: "desmontaje",
    colaboradorId: "col2",
    asignadoPorId: "u2",
    estado: "completada",
    instrucciones: "Desmontaje parcial tren de rodaje.",
    comentarioMecanico: "Desmontaje OK. Esperando repuestos importados.",
    fechaAsignacion: "2026-02-21",
    fechaActualizacion: "2026-02-23",
  },
];
