// Datos reales del checklist "CHECK LIST - EQUIPO GENERICO" provisto por el cliente (SM).
// Generado una sola vez a partir del Excel adjunto; ver docs del PR para el origen.
export const EQUIPO_GENERICO_SECCIONES: { titulo: string; items: { codigo: string; descripcion: string }[] }[] = [
  {
    titulo: "Sistema Motor",
    items: [
      { codigo: "NIVEL_DE_ACEITE_MOTOR", descripcion: "Nivel De Aceite Motor" },
      { codigo: "FUNCIONAMIENTO_DEL_MOTOR", descripcion: "Funcionamiento Del Motor" },
      { codigo: "EFICIENCIA_DE_ARRANQUE", descripcion: "Eficiencia De Arranque" },
      { codigo: "TURBOCOMPRESOR", descripcion: "Turbocompresor" },
      { codigo: "RESPIRADERO_DE_MOTOR", descripcion: "Respiradero De Motor" },
      { codigo: "VARILLA_DE_NIVEL_DE_ACEITE", descripcion: "Varilla De Nivel De Aceite" },
      { codigo: "FUGAS_DE_ACEITE_MOTOR", descripcion: "Fugas De Aceite Motor" },
      { codigo: "SOPORTES_DE_MOTOR", descripcion: "Soportes De Motor" },
      { codigo: "FILTRO_DE_AIRE_PRIMARIO", descripcion: "Filtro De Aire Primario" },
      { codigo: "FILTRO_DE_AIRE_SECUNDARIO", descripcion: "Filtro De Aire Secundario" },
      { codigo: "MULTIPLE_DE_ADMISION", descripcion: "Multiple De Admision" },
      { codigo: "MULTIPLE_DE_ESCAPE", descripcion: "Multiple De Escape" },
      { codigo: "TUBO_DE_ESCAPE", descripcion: "Tubo De Escape" },
      { codigo: "BOMBA_DE_INYECCION", descripcion: "Bomba De Inyeccion" },
      { codigo: "INYECTORES", descripcion: "Inyectores" },
      { codigo: "CANERIAS_DE_COMBUSTIBLE", descripcion: "Cañerias De Combustible" },
      { codigo: "BOMBA_DE_CEBADO_DE_COMBUSTIBLE", descripcion: "Bomba De Cebado De Combustible" },
      { codigo: "FUGAS_DE_COMBUSTIBLE", descripcion: "Fugas De Combustible" },
      { codigo: "FILTRO_DE_PETROLEO", descripcion: "Filtro De Petroleo" },
      { codigo: "FILTRO_DE_ACEITE_DE_MOTOR", descripcion: "Filtro De Aceite De Motor" },
      { codigo: "FILTRO_SEPARADOR_AGUA_COMB", descripcion: "Filtro Separador Agua Comb." },
      { codigo: "TRABA_DE_MOTOR", descripcion: "Traba De Motor" },
      { codigo: "RADIADOR_DE_AGUA", descripcion: "Radiador De Agua" },
      { codigo: "TAPA_DE_RADIADOR", descripcion: "Tapa De Radiador" },
      { codigo: "REFRIGERANTE", descripcion: "Refrigerante" },
      { codigo: "VENTILADOR", descripcion: "Ventilador" },
      { codigo: "FAJA_DE_VENTILADOR", descripcion: "Faja De Ventilador" },
      { codigo: "ESTADO_DE_MANGUERAS", descripcion: "Estado De Mangueras" },
      { codigo: "FUGAS_DE_REFRIGERANTE", descripcion: "Fugas De Refrigerante" },
      { codigo: "GUARDAS_RADIADOR", descripcion: "Guardas Radiador" },
      { codigo: "SOPORTES_RADIADOR", descripcion: "Soportes Radiador" },
      { codigo: "AFTER_COOLER_INTER_COOLER", descripcion: "After Cooler / Inter Cooler" },
      { codigo: "ENFRIADOR_DE_ACEITE_MOTOR", descripcion: "Enfriador De Aceite Motor" },
      { codigo: "TERMOSTATO", descripcion: "Termostato" },
      { codigo: "BOMBA_DE_AGUA", descripcion: "Bomba De Agua" },
    ],
  },
  {
    titulo: "Sistema Transmision/Desplazamiento",
    items: [
      { codigo: "NIVEL_DE_ACEITE_CAJA_DE_CAMBIOS", descripcion: "Nivel De Aceite Caja De Cambios" },
      { codigo: "VARILLA_VISOR_NIVEL_DE_ACEITE", descripcion: "Varilla/Visor Nivel De Aceite" },
      { codigo: "TAPON_DE_DRANAJE_DE_ACEITE", descripcion: "Tapon De Dranaje De Aceite" },
      { codigo: "FILTRO_ACEITE_TRANSMISION", descripcion: "Filtro Aceite Transmision" },
      { codigo: "FUGAS_DE_ACEITE_TRANSMISION", descripcion: "Fugas De Aceite Transmision" },
      { codigo: "TANDEM", descripcion: "Tandem" },
      { codigo: "MOTOR_DE_TRASLACION", descripcion: "Motor De Traslacion" },
      { codigo: "ORUGAS", descripcion: "Orugas" },
      { codigo: "CADENAS", descripcion: "Cadenas" },
      { codigo: "TENSADORES_DE_CADENA", descripcion: "Tensadores De Cadena" },
      { codigo: "SPROCKET", descripcion: "Sprocket" },
      { codigo: "RODILLOS", descripcion: "Rodillos" },
      { codigo: "EJE_CARDAN", descripcion: "Eje Cardan" },
      { codigo: "CRUCETA", descripcion: "Cruceta" },
      { codigo: "RUIDOS_INTERIORES", descripcion: "Ruidos Interiores" },
      { codigo: "EJE_DIFERENCIAL_DELANTERO", descripcion: "Eje Diferencial Delantero" },
      { codigo: "EJE_DIFERENCIAL_POSTERIOR", descripcion: "Eje Diferencial Posterior" },
      { codigo: "NIVEL_DE_ACEITE_DIFERENCIALES", descripcion: "Nivel De Aceite Diferenciales" },
      { codigo: "NIVEL_DE_ACEITES_MANDOS_FINALES", descripcion: "Nivel De Aceites Mandos Finales" },
    ],
  },
  {
    titulo: "Sistema Freno",
    items: [
      { codigo: "EFECTIVIDAD_DE_FRENADO", descripcion: "Efectividad De Frenado" },
      { codigo: "BOMBA_COMPRESOR_DE_FRENO", descripcion: "Bomba / Compresor De Freno" },
      { codigo: "FRENO_DE_ESTACIONAMIENTO", descripcion: "Freno De Estacionamiento" },
    ],
  },
  {
    titulo: "Sistema De Dirección",
    items: [
      { codigo: "NIVEL_DE_ACEITE", descripcion: "Nivel De Aceite" },
      { codigo: "BOMBA_HIDRAULICA_SERVO_DIRECCION", descripcion: "Bomba Hidraulica Servo Direccion" },
      { codigo: "TANQUE_HIDRAULICO", descripcion: "Tanque Hidraulico" },
      { codigo: "MANGUERAS", descripcion: "Mangueras" },
      { codigo: "ROTULAS_PINES_Y_BOCINAS", descripcion: "Rotulas, Pines Y Bocinas" },
      { codigo: "CILINDROS_DE_DIRECCION", descripcion: "Cilindros De Direccion" },
      { codigo: "PIN_DE_TRABA", descripcion: "Pin De Traba" },
    ],
  },
  {
    titulo: "Neumaticos",
    items: [
      { codigo: "LLANTAS_DELANTERAS", descripcion: "Llantas Delanteras" },
      { codigo: "LLANTAS_POSTERIORES", descripcion: "Llantas Posteriores" },
      { codigo: "LLANTA_DE_REPUESTO", descripcion: "Llanta De Repuesto" },
      { codigo: "PERNOS_Y_TUERCAS_DE_SUJECCION", descripcion: "Pernos Y Tuercas De Sujeccion" },
      { codigo: "TRABA_TUERCAS", descripcion: "Traba Tuercas" },
    ],
  },
  {
    titulo: "Cabina Del Operador",
    items: [
      { codigo: "ESTRIBOS_DE_ACCESO", descripcion: "Estribos De Acceso" },
      { codigo: "PASAMANOS", descripcion: "Pasamanos" },
      { codigo: "SISTEMA_DE_PROTECCION_ANTIVUELCO", descripcion: "Sistema De Proteccion Antivuelco" },
      { codigo: "TIMON_DE_DIRECCION", descripcion: "Timon De Direccion" },
      { codigo: "JOYSTICK_UNIVERSAL", descripcion: "Joystick Universal" },
      { codigo: "PALANCAS_ACC_HIDRAULICO", descripcion: "Palancas Acc. Hidraulico" },
      { codigo: "PEDAL_ACELERACION", descripcion: "Pedal Aceleracion" },
      { codigo: "PEDAL_DE_FRENO", descripcion: "Pedal De Freno" },
      { codigo: "PEDAL_DE_NEUTRALIZACION_DE_TRANSM", descripcion: "Pedal De Neutralizacion De Transm." },
      { codigo: "PALANCA_DE_CAMBIOS", descripcion: "Palanca De Cambios" },
      { codigo: "INDICADORES_INDIVIDUALES", descripcion: "Indicadores Individuales" },
      { codigo: "TABLERO_LUCES_FUNCIONAMIENTO_INST", descripcion: "Tablero Luces Funcionamiento Inst" },
      { codigo: "ASIENTO_DEL_OPERADOR", descripcion: "Asiento Del Operador" },
      { codigo: "CINTURON_DE_SEGURIDAD", descripcion: "Cinturon De Seguridad" },
      { codigo: "CODERAS", descripcion: "Coderas" },
      { codigo: "CABEZERA", descripcion: "Cabezera" },
      { codigo: "ESPEJOS_INTERIOR_DE_CABINA", descripcion: "Espejos-Interior De Cabina" },
      { codigo: "FARO_DE_LUZ_EN_CABINA", descripcion: "Faro De Luz En Cabina" },
      { codigo: "RADIO", descripcion: "Radio" },
      { codigo: "PARLANTES", descripcion: "Parlantes" },
      { codigo: "AIRE_ACONDICIONADO", descripcion: "Aire Acondicionado" },
      { codigo: "LUNAS_COMPLETAS", descripcion: "Lunas Completas" },
      { codigo: "ESPEJOS_RETROVISORES", descripcion: "Espejos Retrovisores" },
      { codigo: "ENCENDEDOR", descripcion: "Encendedor" },
      { codigo: "CAJA_DE_ACCESORIOS", descripcion: "Caja De Accesorios" },
    ],
  },
  {
    titulo: "Accesorios Y Herramientas",
    items: [
      { codigo: "LLAVE_DE_RUEDAS", descripcion: "Llave De Ruedas" },
      { codigo: "GATA", descripcion: "Gata" },
      { codigo: "CIRCULINA", descripcion: "Circulina" },
      { codigo: "BOTIQUIN", descripcion: "Botiquin" },
      { codigo: "EXTINTOR", descripcion: "Extintor" },
      { codigo: "TRIANGULO_DE_SEGURIDAD", descripcion: "Triangulo De Seguridad" },
      { codigo: "CONOS_DE_SEGURIDAD", descripcion: "Conos De Seguridad" },
      { codigo: "KIT_ANTIDERRAME", descripcion: "Kit Antiderrame" },
      { codigo: "TACOS", descripcion: "Tacos" },
      { codigo: "EQUIPOS_LHD", descripcion: "Equipos Lhd" },
    ],
  },
  {
    titulo: "Sistema Hidraulico",
    items: [
      { codigo: "CILINDROS_DE_DIRECCION", descripcion: "Cilindros De Dirección" },
      { codigo: "CILINDROS_DE_LEVANTE", descripcion: "Cilindros De Levante" },
      { codigo: "CILINDROS_DE_VOLTEO", descripcion: "Cilindros De Volteo" },
    ],
  },
  {
    titulo: "Sistema Electrico",
    items: [
      { codigo: "BATERIAS", descripcion: "Baterias" },
      { codigo: "CAJAS_DE_CONEXION", descripcion: "Cajas De Conexión" },
      { codigo: "PARADAS_DE_EMERGENCIA", descripcion: "Paradas De Emergencia" },
      { codigo: "FAROS_DELANTEROS", descripcion: "Faros Delanteros" },
      { codigo: "LUCES_TRASERAS", descripcion: "Luces Traseras" },
      { codigo: "LUZ_DE_FRENO", descripcion: "Luz De Freno" },
      { codigo: "LUCES_OPCIONALES", descripcion: "Luces Opcionales" },
    ],
  },
  {
    titulo: "Tren De Potencia",
    items: [
      { codigo: "MOTOR_DIESEL", descripcion: "Motor Diesel" },
      { codigo: "CONVERTIDOR_DE_TORQUE", descripcion: "Convertidor De Torque" },
      { codigo: "TRANSMISION", descripcion: "Transmision" },
      { codigo: "EJE_DELANTERO", descripcion: "Eje Delantero" },
      { codigo: "EJE_TRASERO", descripcion: "Eje Trasero" },
    ],
  },
  {
    titulo: "Estructural",
    items: [
      { codigo: "BALDE", descripcion: "Balde" },
      { codigo: "DOG_BONE", descripcion: "Dog Bone" },
      { codigo: "BARRA_Z", descripcion: "Barra Z" },
      { codigo: "BOOM", descripcion: "Boom" },
      { codigo: "CHASIS_DELANTERO", descripcion: "Chasis Delantero" },
      { codigo: "CHASIS_TRASERO", descripcion: "Chasis Trasero" },
      { codigo: "CABINA", descripcion: "Cabina" },
      { codigo: "TAPAS_Y_PROTECCIONES", descripcion: "Tapas Y Protecciones" },
      { codigo: "PASADORES_BUJES_Y_TAPAS_ART_SUPERIOR", descripcion: "Pasadores, Bujes Y Tapas  Art. Superior" },
      { codigo: "PASADORES_BUJES_Y_TAPAS_ART_INFERIOR", descripcion: "Pasadores, Bujes Y Tapas  Art. Inferior" },
      { codigo: "PASADORES_BUJES_Y_TAPAS_BOOM", descripcion: "Pasadores, Bujes Y Tapas Boom" },
      { codigo: "PASADORES_BUJES_Y_TAPAS_DOG_BONE", descripcion: "Pasadores, Bujes Y Tapas Dog Bone" },
      { codigo: "PASADORES_BUJES_Y_TAPAS_BALDE", descripcion: "Pasadores, Bujes Y Tapas Balde" },
      { codigo: "TOPES_DE_BALDE", descripcion: "Topes De Balde" },
    ],
  },
  {
    titulo: "Sistema De Seguridad",
    items: [
      { codigo: "PARADA_DE_EMERGENCIA_CABINA", descripcion: "Parada De Emergencia Cabina" },
      { codigo: "PARADAS_DE_EMERGENCIAS_EXTREMO_POSTERIOR", descripcion: "Paradas De Emergencias Extremo Posterior" },
      { codigo: "DIRECCION_DE_EMERGENCIA", descripcion: "Dirección De Emergencia" },
      { codigo: "ALARMA_MARCHA_ATRAS", descripcion: "Alarma Marcha Atrás" },
      { codigo: "CINTURON_DE_SEGURIDAD", descripcion: "Cinturón De Seguridad" },
      { codigo: "FUNCIONAMIENTO_FRENOS_DE_SERVICIO", descripcion: "Funcionamiento Frenos De Servicio" },
      { codigo: "FARO_DE_DESTELLO_GIRATORIO_BALIZA", descripcion: "Faro De Destello Giratorio  (Baliza)" },
      { codigo: "LOGOS_DE_SEGURIDAD", descripcion: "Logos De Seguridad" },
    ],
  },
];